(function(){
const focusAreas = [
  { name: "Partnering", short: "Partnering", description: "Build effective relationships to accomplish mutual goals." },
  { name: "Communicating", short: "Communicating", description: "Communicate clearly across mediums and stakeholders." },
  { name: "Driving results", short: "Driving results", description: "Work autonomously, take ownership, and deliver impact." },
  { name: "Growing continuously", short: "Growing", description: "See opportunities to learn, adapt, and grow." },
  { name: "Product thinking", short: "Product thinking", description: "Influence strategy, find the right problem, and build effective products." },
];

const anchorStoryMap = [
  {
    focus: "Partnering",
    anchorId: "acquisition-onboarding",
    backupId: "storybook-bet",
    rationale: "Lead with the partnership structure that surfaced a major risk; use Storybook when the question is about disagreement or making room for another team’s direction.",
  },
  {
    focus: "Communicating",
    anchorId: "home-depot-living-preread",
    backupId: "adplist-designing-for-comprehension",
    rationale: "Lead with proactive cross-functional alignment; use ADPList when the question is about adapting the medium to create comprehension.",
  },
  {
    focus: "Driving results",
    anchorId: "supplier-one",
    backupId: "figma-subsystem",
    rationale: "Lead with the 0→1 platform decision and launch; use the subsystem to show how reusable infrastructure shifted the team toward higher-order product work and earned organic adoption beyond the Supplier One team.",
  },
  {
    focus: "Growing continuously",
    anchorId: "size-overbuild",
    backupId: "local-pickup",
    rationale: "Lead with a clear design miss and the restraint it taught you; use local discovery when the question is about challenging your own causal assumption.",
  },
  {
    focus: "Product thinking",
    anchorId: "ai-shopping-agent",
    backupId: "size-journey",
    rationale: "Lead with AI product strategy, trust, and system ownership; use size when the question is about reframing a feature into an end-to-end product problem.",
  },
];

const evidenceClassifications = [
  {
    status: "ready",
    label: "Safe to use",
    guidance: "State these directly and keep the scope attached to the number.",
    items: [
      "Home Depot’s acquisition onboarding involved more than one million customers.",
      "Early schema discovery saved approximately six weeks, and the migration landed on time.",
      "Home Depot publicly reported $151.2B in FY2021 sales and described Pros as approximately half of sales, implying roughly $75.6B in annual business scale. The two-million-plus customer count is the internal platform scope, not an acquisition price.",
      "Walmart’s supplier documentation confirms Supplier One as a unified experience and directs all eligible US 1P suppliers to use it as of February 22, 2024.",
      "Supplier One was shaped by identifying common functions and jobs across roughly 100 fragmented supplier applications spanning inventory, purchase history, payments, account management, onboarding, orders, and other data-dense B2B workflows.",
      "Internal Supplier One launch KPIs: 500+ of Walmart’s highest-revenue supplier companies onboarded; 30% of invited suppliers converted; and average onboarding fell from 48 days to five days from application start through approval.",
      "Internal Supplier One six-month KPIs: combined support contacts fell 20%, logistics costs fell 30%, and the platform delivered 4× ROI.",
      "The Walmart Merchant team’s Item 360 product organically adopted Supplier One’s dynamic table pattern because it made dense product data easier to consume without overwhelming the interface.",
      "Figma analytics showed increases and spikes in people using or copying Supplier One assets into their designs. This is behavioral evidence of cross-team adoption; the exact usage count is unknown.",
      "Roles and permissions served more than two million Pro customers.",
      "eBay publicly announced the AI Shopping Agent and confirmed it was live to a small percentage of US customers with a rolling expansion.",
      "Lia DiValentin is a named inventor on the published US patent application ‘Immersive Item Cards,’ US 2026/0187710 A1, filed December 26, 2024 and published July 2, 2026.",
      "The Storybook environment became the fastest option for usability and A/B testing.",
    ],
  },
  {
    status: "qualify",
    label: "Use with qualification",
    guidance: "Name whether the number is approximate, estimated, or a target.",
    items: [
      "The roughly $1M Home Depot impact is an estimate based on six weeks of engineering and rearchitecture effort.",
      "Supplier One’s customer-satisfaction score in ASUS—the internal measurement platform used at the time—was targeted at 80 out of 100; do not present the target as an achieved result.",
      "The approximately 1% AI Shopping Agent production cohort is internal rollout knowledge; public eBay materials say only ‘a small percentage’ or ‘a small subset’ of US customers.",
      "Across projects, stakeholder buy-in and shared context accelerated delivery by unlocking decisions, resourcing, and implementation leverage. Present this as a repeated qualitative pattern; say ‘by months’ only for a project with a baseline and revised timeline.",
    ],
  },
  {
    status: "confirm",
    label: "Confirm before interview",
    guidance: "Do not turn these into hard facts until the supporting detail is clear.",
    items: [
      "ASUS customer satisfaction was measured annually after launch, but the achieved post-launch score still needs to be recovered. Until then, use 80 out of 100 only as the target.",
      "The ‘roughly 10× faster’ Figma-subsystem claim needs a defensible before-and-after timing comparison before it can be used as a measured outcome. Until then, describe the eliminated manual recreation and strategic shift qualitatively.",
      "A direct CEO statement about the AI Shopping Agent has not been found. The public launch article quotes eBay’s CTO and Chief AI Officer; Q2 2025 results list the agent as a business highlight but do not attribute that statement directly to the CEO.",
      "A measurable result for roles and permissions and for the simplified size experience.",
      "PM, engineering, research, and operational partners for each anchor story.",
    ],
  },
];

const stories = [
  {
    id: "ai-shopping-agent",
    title: "AI Shopping Agent + MCP framework",
    company: "eBay",
    role: "Staff Product Designer · 2024–2026",
    section: "Presentation follow-up",
    focus: ["Driving results", "Product thinking"],
    rows: [
      { label: "Situation", text: "eBay was moving to an AI-first, agentic marketplace. The buyer and seller experience was still undefined—ambiguous, fast-moving, and high visibility." },
      { label: "Action", text: "I defined the experience vision for the AI Shopping Agent—conversational, inline picks plus expert guidance across the journey—and architected the end-to-end MCP experience layer connecting on-platform agents to third parties like OpenAI. I also redesigned the search-results ecosystem for AI-first browsing." },
      { label: "Result", text: "eBay publicly announced the Shopping Agent and confirmed it was live to a small percentage of US customers with rolling expansion; internally, the controlled production cohort was approximately 1%. The launch article featured the CTO and Chief AI Officer. I am also a named inventor on the published US patent application ‘Immersive Item Cards’ (US 2026/0187710 A1), which covers the rotatable, information-rich item-card interaction." },
      { label: "Learned", text: "In agentic products, trust and failure states are the product. Designing what happens when the agent is wrong mattered more than the happy path." },
    ],
    tradeoffs: [
      {
        title: "Embedded AI versus a separate destination",
        statement: "We could have made the agent a separate conversational destination. I chose to integrate recommendations and guidance into the existing shopping journey so buyers retained their search and item context. That reduced mode switching, although it gave us less room for unrestricted conversation.",
        evidence: "Bring the prototype, research, or journey evidence showing where preserving search and item context mattered. Do not imply a measured reduction in mode switching unless you have the data.",
        reconsider: "Reconsider a separate destination if customers deliberately seek an open-ended assistant, need longer multi-step planning, or embedded guidance no longer has enough space to complete the job.",
      },
      {
        title: "Immediate action versus clarification",
        statement: "The agent could infer intent and act immediately, or pause when an error would be expensive. I chose targeted clarification for genuinely ambiguous requests. We accepted a small amount of friction to reduce wrong results and recovery work.",
        evidence: "Bring one genuinely ambiguous query, the failure it could create, and any prototype, usability, null-result, or recovery evidence that shaped the decision.",
        reconsider: "Reconsider clarification when confidence is high, the action is easy to reverse, or the prompt would add more burden than the potential error.",
      },
      {
        title: "AI information versus interface density and control",
        statement: "The results page was already information-dense. I used progressive disclosure through the flip-card pattern so AI signals could be available without permanently expanding every item card. We gave up immediate visibility of every signal to preserve scanning, comprehension, and user control.",
        evidence: "Bring the density comparison, prototype feedback, or scanning and comprehension evidence that supports progressive disclosure. Keep the tradeoff qualitative if no metric was captured.",
        reconsider: "Reconsider hiding a signal when it is essential to the purchase decision, consistently missed, or valuable enough to justify permanent space on the card.",
      },
    ],
    probe: "Expect: “What was your specific contribution versus the team’s?” Answer crisply: you owned the experience vision and MCP layer. Name the PM and engineering leads you co-owned decisions with, and prepare three major design tradeoffs. Do not claim a direct CEO citation unless you recover a separate source.",
    prompt: "Walk me through a project from your presentation and the specific decisions you owned.",
  },
  {
    id: "acquisition-onboarding",
    title: "The acquisition that almost broke onboarding",
    company: "Home Depot",
    role: "Senior UX Designer · 2018–2022",
    section: "Five focus areas",
    focus: ["Partnering", "Driving results"],
    rows: [
      { label: "Business scale", text: "This work sat inside a platform serving more than two million Home Depot Pro customers. Home Depot reported $151.2B in FY2021 sales and publicly described Pros as approximately half of sales, implying roughly $75.6B in annual business scale. That is a derived estimate of the Pro business—not an acquisition price." },
      { label: "Situation", text: "Home Depot acquired a third-party company and needed to absorb more than one million of its customers into our Pro onboarding flow. Their team was being treated as a handoff, not a partner." },
      { label: "Action", text: "I recruited their head PM onto our working team—not as a stakeholder to inform, but as a co-owner—and ran a design sprint with her embedded." },
      { label: "Turning point", text: "She flagged an API and data-model mismatch nobody on our side knew about: their database split first and last name; ours captured a single company-name field." },
      { label: "Result", text: "We adjusted the schema before build instead of re-architecting after migration. That saved roughly six weeks of engineering time—about $1M in development effort—and the migration landed on time." },
      { label: "Learned", text: "The fastest path to a mutual goal is giving the other side ownership. Relationships surface risks that documents never do." },
    ],
    say: "I changed how we ran the integration—partner embedded, not handed off—and that structure surfaced a six-week, seven-figure risk before a line of code was written.",
    avoid: "“She saved us.” It hands away your credit. Own the partnering move that made the discovery possible.",
    probe: "If pressed on $1M: six weeks of a full-stack team plus a re-architecture of the acquisition pipeline. The six weeks is the hard fact; don’t over-defend the estimate.",
    prompt: "Tell me about a partnership that changed the outcome of a difficult project.",
  },
  {
    id: "clarify-intent",
    title: "Don’t assume intent—determine it",
    company: "eBay",
    role: "Search disambiguation",
    section: "Five focus areas",
    focus: ["Product thinking", "Communicating"],
    rows: [
      { label: "Situation", text: "For ambiguous queries such as “size,” the team default was to guess intent and act. Wrong guesses created null results and dead ends." },
      { label: "Action", text: "I pushed a principle: don’t assume—clarify before acting. I designed a disambiguation step for genuinely ambiguous cases and made the product case that a little friction beat a wrong result." },
      { label: "Result", text: "Users found it helpful exactly where it mattered. The principle carried into how the AI Shopping Agent handles unclear asks." },
      { label: "Learned", text: "The right amount of friction is a design decision, not a bug. Scope it tightly." },
    ],
    say: "I set the principle—clarify before acting—and it became one of our experience principles for AI commerce.",
    avoid: "Don’t claim the pattern used by every major AI assistant was born here. That overreach undercuts the story.",
    probe: "Add a metric—task completion, null-result rate, or CSAT—and the role of the person you had to align. Then this can double as a partnering story.",
    prompt: "Tell me about a time you introduced friction because it made the product better.",
  },
  {
    id: "supplier-one",
    title: "Supplier One, 0→1",
    company: "Walmart",
    role: "Senior Product Designer · 2022–2024",
    section: "Five focus areas",
    focus: ["Driving results", "Product thinking", "Partnering"],
    rows: [
      { label: "Situation", text: "Walmart’s B2B supplier and merchant ecosystem was fragmented across roughly 100 supplier applications for inventory, purchase history, payments, account management, onboarding, orders, and other complex data-driven workflows. From application start through approval, the legacy onboarding process averaged 48 days." },
      { label: "Product strategy", text: "I helped identify the common functions and jobs across those applications, made the case to consolidate them into Supplier One instead of redesigning each tool one by one, won executive buy-in, and led end-to-end design from concept to launch. Usability research and A/B tests focused the highest-volume workflows." },
      { label: "Designed to scale", text: "For the MVP, we paired shared functionality with reusable complex components and page templates. That foundation was deliberately structured so the team could add pages and post-launch functionality as remaining supplier needs emerged without recreating the product infrastructure each time." },
      { label: "First-launch results", text: "According to our internal launch KPIs, 30% of invited suppliers converted, producing a first-launch cohort of more than 500 of Walmart’s highest-revenue supplier companies. Average onboarding fell from 48 days to five days—a calculated improvement of roughly 90%—measured from application start through approval." },
      { label: "Six-month outcomes", text: "According to our internal six-month KPIs, the unified platform reduced combined support contacts across tickets and the call center by 20%, reduced logistics costs by 30%, and delivered 4× ROI. Customer satisfaction was measured annually in ASUS, Walmart’s internal measurement platform at the time. The target was 80 out of 100; do not present 80 as the achieved score unless the annual result is recovered." },
      { label: "Learned", text: "Ownership means owning the metric, not the mockup." },
    ],
    probe: "For Product Thinking, lead with how you found common jobs across roughly 100 fragmented tools and turned them into one platform architecture. For Driving Results, lead with the 48-to-five-day change, 500+ companies, and 30% invitation conversion; save the six-month cost, support, and ROI results for the follow-up. For Partnering, name the supplier, merchant, product, engineering, and operational partners who helped define the common functions. ASUS was measured annually; keep 80 out of 100 labeled as the target unless you recover the achieved score.",
    prompt: "Tell me about a 0→1 product where you influenced the business strategy.",
  },
  {
    id: "figma-subsystem",
    title: "Supplier One: from component churn to organizational leverage",
    company: "Walmart",
    role: "Design infrastructure · Cross-team influence",
    section: "Five focus areas",
    focus: ["Driving results", "Product thinking", "Partnering", "Communicating"],
    flags: ["Cross-team adoption", "Unresolved speed metric"],
    rows: [
      { label: "Situation", text: "Supplier One’s inventory and operational dashboards depended on dense tables and complex data states. A complex component could require roughly 200–400 permutations; manually recreating those states would have turned MVP delivery into production churn." },
      { label: "System move", text: "I architected a product-specific Figma subsystem on top of the core design system. Configurable components encoded the permutations as reusable variants, so the team could generate the state it needed instead of redrawing the same component hundreds of times." },
      { label: "MVP and post-launch scale", text: "We paired those components with reusable page templates for the MVP and designed the foundation to support additional pages and functionality after launch as unmet supplier needs surfaced." },
      { label: "Strategic effect", text: "Removing repetitive component production shifted design time toward information architecture, page composition, complex data flows, and the strategic question of how suppliers should understand and move through the product." },
      { label: "Organic cross-team adoption", text: "The Walmart Merchant team working on Item 360 adopted Supplier One’s dynamic table pattern because it displayed dense product information more effectively and made the interface feel less overwhelming." },
      { label: "Adoption evidence", text: "Figma analytics showed increases and spikes in people using or copying Supplier One assets into their own designs. That is behavioral evidence of organizational leverage and cross-team adoption, but the exact usage count is unknown and should not be invented." },
      { label: "Result", text: "The subsystem became more than a component library: it created reusable product infrastructure, protected the team’s attention for higher-order product decisions, and demonstrated influence when another Walmart team adopted the pattern. A precise speed multiplier remains unresolved until a defensible before-and-after timing comparison is recovered." },
      { label: "Learned", text: "System leadership is not the number of components produced. It is the product judgment the system gives back to the team and the capability it creates beyond the team that built it." },
    ],
    say: "I turned a 200-to-400-permutation production problem into reusable product infrastructure. That gave our designers more time for information architecture and complex workflows, and the strongest organizational signal was organic adoption: Item 360 used our table pattern and Figma analytics showed other teams copying Supplier One assets.",
    avoid: "Do not state ‘10× faster’ as a measured outcome without before-and-after timing, do not invent an adoption count from the Figma spikes, and do not describe 200–400 permutations as 200–400 separately designed components.",
    probe: "Expect: ‘How did you measure leverage?’ Use two evidence levels: Item 360 is the concrete adoption example; the Figma analytics trend is broader behavioral evidence with no exact count. If you want to restore a speed multiplier, reconstruct the old time per state or page, the new configuration time, the number of repeated states, and the comparable delivery period. Otherwise leave 10× unresolved and describe the strategic capacity shift.",
    prompt: "Tell me about a system you created that changed how your team worked and influenced teams beyond it.",
  },
  {
    id: "local-pickup",
    title: "Local discovery: from a weak cost assumption to a service-system hypothesis",
    company: "eBay",
    role: "Reframing discovery and fulfillment",
    section: "Five focus areas",
    focus: ["Product thinking", "Growing continuously"],
    flags: ["Growth story"],
    rows: [
      { label: "Situation", text: "Tariff volatility exposed unpredictable cost pressure across the marketplace. I looked for a structural response that could protect buyers, sellers, and eBay instead of simply moving the cost from one participant to another." },
      { label: "The honest miss", text: "My first hypothesis overconnected tariffs and local pickup. An item can be nearby and still have imported origins, while local fulfillment still carries transportation, labor, coordination, handoff, and time costs. Local availability does not automatically create tariff relief or lower cost to serve." },
      { label: "The pivot", text: "We moved from treating local pickup as the answer to improving discovery of inventory already available nearby. That was a more defensible customer problem: help buyers understand what they can get locally, when they can get it, and what tradeoffs they are making." },
      { label: "Why agentic search", text: "Local discovery became a strong agentic-search use case when the request involved several constraints at once—item, budget, distance, timing, condition, and acceptable substitutes. The agent could interpret intent, compare nearby options, and explain tradeoffs. If the job were only toggling a local filter, conventional search would be simpler and more appropriate." },
      { label: "External signal, not a partnership", text: "In 2026, GameStop proposed acquiring eBay and suggested using its stores as authentication, intake, fulfillment, and shipping nodes; eBay rejected the proposal. The store-network concept is still a useful public signal that physical service touchpoints are worth exploring, but it is not an active eBay–GameStop partnership." },
      { label: "Future service hypothesis", text: "Building on that signal, I would explore secure drop-off lockers or staffed intake points as one possible service-design layer for selected categories. The experience would connect local discovery, seller drop-off, chain of custody, buyer pickup, returns, and status communication—not just add a locker to the interface." },
      { label: "Stress test", text: "The model only earns investment if item density and throughput justify the footprint; custody, loss, damage, fraud, authentication, storage, accessibility, and liability are clearly owned; and the end-to-end economics beat home shipping or person-to-person pickup. I would begin with a narrow category and geography, then test completion rate, cost per handoff, cycle time, incidents, and repeat use." },
      { label: "What I changed", text: "I learned to separate origin, discovery, and fulfillment because each solves a different problem. The leadership move was not defending the first idea—it was identifying the broken causal link, pivoting to the stronger customer problem, and preserving the best future hypothesis with explicit evidence gates." },
    ],
    say: "I did not defend a weak causal link between tariffs and local pickup. I separated the problems, pivoted to local inventory discovery, clarified where agentic search added value, and turned the fulfillment concept into a testable service hypothesis.",
    avoid: "Do not describe eBay and GameStop as partners or imply that either company announced lockers. GameStop proposed the store-network concept as part of an acquisition bid that eBay rejected; the locker layer is your adjacent hypothesis. Also avoid claiming that local inventory removes tariffs or automatically lowers total cost.",
    probe: "Add the customer or prototype evidence that supported the discovery pivot, one multi-constraint query the agent handled better than filters, and the category, geography, and success thresholds you would use for a locker pilot.",
    prompt: "Tell me about a hypothesis you challenged and converted into a stronger product strategy.",
  },
  {
    id: "size-journey",
    title: "Size: from search problem to buyer-journey problem",
    company: "eBay",
    role: "Personalization for fit",
    section: "Five focus areas",
    focus: ["Product thinking", "Partnering"],
    rows: [
      { label: "Situation", text: "The problem came to me scoped to search only, but finding your fit doesn’t fail only in search—it fails everywhere the data is inconsistent." },
      { label: "Action", text: "I reframed the work across homepage recommendations, search, results, product pages, browse, cart, checkout, and a post-purchase feedback loop. Underneath, we needed to clean and re-architect size data so it could power fit." },
      { label: "Turning point", text: "Another team had already done a large size-personalization effort. Instead of duplicating it, I contacted their lead designer and ran a joint sprint." },
      { label: "Result", text: "We wrote an SOP for one size-component pattern and one design language across the journey, with the same interpretation on buyer and seller sides. That one-to-one mapping made seller fit data meaningful for the first time." },
      { label: "Learned", text: "Expand the problem when the evidence demands it, while keeping the interface restrained." },
    ],
    probe: "Use this for influencing product strategy. Keep the surface list to one breath and spend time on the data insight and partnership. Add a return-rate, conversion, or fit-complaint metric if available.",
    prompt: "Tell me about a time you reframed the problem and changed product strategy.",
  },
  {
    id: "size-overbuild",
    title: "Size personalization: I over-built, then I cut",
    company: "eBay",
    role: "Search disambiguation → end-to-end personalization",
    section: "Five focus areas",
    focus: ["Growing continuously", "Product thinking"],
    flags: ["Difficult project", "Anchor story"],
    rows: [
      { label: "Situation", text: "The work started as search disambiguation and expanded into end-to-end personalization with sophisticated size profiles. Size is a genuinely hard space." },
      { label: "What went wrong", text: "We built a thick UI across the journey. It didn’t need that much uplift—I let the interface scope grow with the ambition instead of the evidence. That was my call." },
      { label: "Action", text: "I decided to pare it back by asking how much of the solution had earned its place. We refined it into a subtle, integrated experience instead of an in-your-face system." },
      { label: "Learned", text: "Restraint is a senior skill. Complexity in the problem doesn’t justify complexity in the UI." },
    ],
    probe: "Use this for a difficult project and as the primary growth story. Add a number for what the subtler design bought—adoption, fewer drop-offs, or lower engineering cost.",
    prompt: "Tell me about something you designed that did not work—and what you changed.",
  },
  {
    id: "roles-permissions",
    title: "Roles & permissions for 2M+ Pro customers",
    company: "Home Depot",
    role: "Account management ecosystem",
    section: "Five focus areas",
    focus: ["Communicating", "Partnering"],
    rows: [
      { label: "Situation", text: "I owned the Pro account ecosystem—roles, permissions, groups, and enterprise workflows—serving more than two million professional customers with very different organization shapes." },
      { label: "Action", text: "I translated a permissions matrix into something a contractor’s office manager could use. I made different artifacts for different rooms: flows for engineering and one-page narratives for leadership." },
      { label: "Result", text: "The system shipped at scale. Add a support-ticket, adoption, or setup-time metric." },
      { label: "Learned", text: "Communicating effectively means changing the artifact, not just the words." },
    ],
    probe: "Use this for communication across stakeholders. Contrast the artifact engineering needed with the one leadership needed.",
    prompt: "How have you adapted the way you communicate for different stakeholders?",
  },
  {
    id: "figma-mcp-matrix",
    title: "Figma → VS Code via MCP, and the 200-variant matrix",
    company: "eBay",
    role: "Design infrastructure",
    section: "Five focus areas",
    focus: ["Product thinking", "Communicating"],
    rows: [
      { label: "Situation", text: "Item cards had category-specific display logic across more than 200 variants. Handoff was slow and lossy." },
      { label: "Action", text: "I built a logic matrix using Figma Make and Excel, plus an MCP integration so engineers could read Figma as the live source of truth and sync tokens. I also introduced NotebookLM to turn interview data into a queryable world data model." },
      { label: "Result", text: "Design-to-engineering cycles became measurably shorter and prioritization stayed grounded in evidence." },
      { label: "Learned", text: "The best handoff removes translation rather than adding documentation." },
    ],
    probe: "Use this for technical fluency and working with engineers. Keep it under 60 seconds; it is a supporting story.",
    prompt: "Tell me about a system you created to improve design and engineering collaboration.",
  },
  {
    id: "storybook-bet",
    title: "The Storybook library I didn’t want",
    company: "eBay",
    role: "Letting a team build outside the design system",
    section: "Two stories they will ask for",
    focus: ["Partnering", "Growing continuously"],
    flags: ["Against my vision", "Anchor story"],
    rows: [
      { label: "Situation", text: "A team, partly interns, wanted to build a separate Storybook component library from scratch to speed production and testing. My vision was one system and one source of truth." },
      { label: "Action", text: "I disagreed openly, then made a leadership call: learning velocity over system purity. I set guardrails for what it was and was not for, and stayed close instead of blocking." },
      { label: "Turning point", text: "It became our fastest environment for usability testing and pulling new components into A/B tests. Something I would have vetoed became infrastructure I relied on." },
      { label: "Learned", text: "Purity of the system isn’t the goal—velocity of learning is. Now I ask what something will let us learn faster before I ask whether it fits the system." },
    ],
    say: "I was wrong about the cost of a second library and right to stay close to it. Both mattered.",
    avoid: "Don’t frame it as letting interns do a side project. It was a deliberate bet you did not agree with and still made room for.",
    prompt: "Tell me about a time you supported a direction that went against your design vision.",
  },
  {
    id: "video-infrastructure",
    title: "Video ads: flagging infrastructure risk before it hit",
    company: "eBay",
    role: "Ads in the search-results redesign",
    section: "Two stories they will ask for",
    focus: ["Product thinking", "Partnering"],
    rows: [
      { label: "Situation", text: "Video ads were entering search as eBay adopted video broadly. Nobody on the feature team was discussing the storage and system-load implications." },
      { label: "Action", text: "I flagged it early and took it to engineering and product as a design-driven infrastructure question, not a nice-to-have." },
      { label: "Result", text: "Advertisers reduced content size; we wrote SOP limits under 60 seconds with size and format constraints; and I designed graceful fallbacks for stalled or failed video so the ad and results page still worked. The pattern carried into other video surfaces." },
      { label: "Pattern recognition", text: "I had seen the same failure mode while running CMS platforms for Army.mil and TASB. Twelve years of platform work helped me spot it before the ads team did." },
      { label: "Learned", text: "A designer who sees the system behind the surface gets invited into infrastructure decisions." },
    ],
    probe: "Use this for a problem nobody else owned or working with engineering. Saying where you learned the pattern turns a good catch into evidence of depth.",
    prompt: "Tell me about a risk you saw before anyone else owned it.",
  },
  {
    id: "ad-feedback",
    title: "Fighting for ad feedback in the MVP",
    company: "eBay",
    role: "Ads in the search-results redesign",
    section: "Two stories they will ask for",
    focus: ["Product thinking", "Driving results"],
    flags: ["Backup"],
    rows: [
      { label: "Situation", text: "The “hide this ad / not relevant” control kept getting scoped out of MVP because the team feared fewer impressions." },
      { label: "Action", text: "I argued that feedback closes a loop to sellers so ads land where they are relevant, strengthening the ad product rather than weakening it. I embedded the control in the component instead of treating it as a bolt-on." },
      { label: "Result", text: "Fill in whether it shipped in MVP, shipped later, or has not shipped. If it did not, explain how you disagreed and committed after losing the argument." },
      { label: "Learned", text: "Make the user case and the P&L case in the same breath." },
    ],
    probe: "This is a product-thinking story unless you lost the decision and committed anyway. Add the actual outcome before using it as an “against my vision” example.",
    prompt: "Tell me about a product decision you fought for using both user and business evidence.",
  },
  {
    id: "accessibility-guild",
    title: "Led the accessibility guild for six months",
    company: "Home Depot",
    role: "Buyer experience under legal scrutiny",
    section: "Leading beyond the seat",
    focus: ["Partnering", "Driving results"],
    rows: [
      { label: "Situation", text: "Parts of the buyer experience were under legal scrutiny for accessibility. There was no owner or process, and most of the organization did not know the standards." },
      { label: "Action", text: "I created and led a monthly guild with engineering and development leads. We audited the highest-risk surfaces first, decided fixes together, and converted each decision into shippable backlog stories. I also taught the standards so the practice would stick." },
      { label: "Result", text: "Legally exposed surfaces were fixed, the audit-to-backlog loop continued after I stepped away, and the design team learned WCAG. Add the number of issues closed or surfaces cleared." },
      { label: "Learned", text: "The output wasn’t accessible screens—it was an operating model other people could run." },
    ],
    say: "I turned a legal liability into an operating model with owners, a cadence, and a backlog—and it kept running after I stepped away.",
    prompt: "Tell me about a change you led that continued after you stepped away.",
  },
  {
    id: "ai-workflow-sprints",
    title: "First AI-in-workflow sprint—and the ones after",
    company: "Walmart · eBay",
    role: "Brown-bag sprints",
    section: "Leading beyond the seat",
    focus: ["Growing continuously", "Communicating"],
    rows: [
      { label: "Situation", text: "AI tools were arriving; designers were curious, unstructured, and nervous about what the shift meant for their value." },
      { label: "Action", text: "I designed and ran Walmart’s first brown-bag AI sprint, simulating an end-to-end design workflow in one day. At eBay I ran a second sprint focused on connecting and scaling deliverables across the workflow." },
      { label: "Result", text: "The teams left with a shared method, not a demo. Add the number of designers and one concrete workflow change that persisted." },
      { label: "Learned", text: "Adoption comes from simulating the real job in a day, not from a tool tour." },
    ],
    probe: "Use this for how you stay ahead or help others grow. Tell it as service to the team.",
    prompt: "How do you help a team learn and adopt a new way of working?",
  },
  {
    id: "regulatory-markets",
    title: "One item-card solution for four markets",
    company: "eBay",
    role: "International regulatory committee",
    section: "Leading beyond the seat",
    focus: ["Product thinking", "Partnering"],
    rows: [
      { label: "Situation", text: "International laws dictate what must appear on a product card, and the requirements differ by market." },
      { label: "Action", text: "I served on the regulatory committee, worked through international standards, and designed one end-to-end item-card solution satisfying the US, UK, Germany and EU, and Australia instead of creating four forks." },
      { label: "Result", text: "The pattern was compliant by design and gave the organization one solution to maintain. Add engineering forks or legal-review cycles saved." },
      { label: "Learned", text: "Constraint fluency can turn regional exceptions into a scalable system." },
    ],
    probe: "Use this for designing under constraints you did not set. It shows you were trusted in rooms beyond design.",
    prompt: "Tell me about a product you designed under legal or market constraints.",
  },
  {
    id: "mentoring-leverage",
    title: "Mentoring designers to show their leverage in an AI era",
    company: "Walmart · eBay",
    role: "Reviews, sprints, and the subsystem",
    section: "Leading beyond the seat",
    focus: ["Growing continuously", "Communicating"],
    rows: [
      { label: "Situation", text: "Designers struggled to articulate their value in reviews once everyone had AI tools. Others needed to build with the subsystem, not around it." },
      { label: "Action", text: "I coached designers to frame impact, judgment, systems, and leverage over output. I taught the subsystem hands-on and joined sprints across teams as the domain-depth partner." },
      { label: "Result", text: "Add one person and one outcome: a promotion, a review that landed, or a team that shipped faster because of the teaching. One concrete person beats “mentored many.”" },
      { label: "Learned", text: "At the next level, your impact is increasingly visible in what other people can do." },
    ],
    say: "I’ve been building leverage in others for years—that is the part of the next level I’ve already been doing.",
    avoid: "Keep real frustration about recognition out of the interview answer. Center the designer’s outcome and what you learned as a leader.",
    prompt: "Tell me about someone you helped grow and the impact of your mentorship.",
  },
  {
    id: "army-library",
    title: "Army.mil: open-source component library in 2014",
    company: "SAIC / Army",
    role: "UX Designer · 2014–2016",
    section: "Resume through-line",
    focus: ["Product thinking", "Driving results"],
    rows: [
      { label: "Situation", text: "Army digital properties were fragmented, and design thinking and UX research were not part of the agile workflow." },
      { label: "Action", text: "I directed the Army.mil flagship redesign and News & Information iOS app, defined the first open-source UI component library for Army digital properties, and introduced design thinking and research into agile delivery." },
      { label: "Result", text: "The work won a DoD Thomas Jefferson Award for Outstanding Flagship Website and drove 125K-plus engagement on a national campaign." },
      { label: "Learned", text: "Systems thinking has been the through-line of my career, not a recent addition." },
    ],
    probe: "Use as one line in the career narrative. It proves you were doing design systems before the term was common.",
    prompt: "Walk me through the through-line in your career.",
  },
  {
    id: "tasb-strategy",
    title: "TASB: strategy for every digital property",
    company: "TASB",
    role: "Lead UX Designer · 2017–2018",
    section: "Resume through-line",
    focus: ["Driving results", "Communicating"],
    rows: [
      { label: "Action", text: "I led the TASB.org information-architecture redesign, launched an organization-wide design system, instituted WCAG 2.1 AA, and directed the research program from interviews and card sorting through journey mapping and usability testing." },
      { label: "Result", text: "The work earned an NSPRA Award of Excellence." },
      { label: "Learned", text: "Strategy becomes credible when the research muscle and operating system support it." },
    ],
    probe: "Use this when asked whether you have owned strategy rather than only execution.",
    prompt: "Tell me about a role where you owned experience strategy end to end.",
  },
  {
    id: "pro-migration-strategy",
    title: "UX strategy for migrating 2M+ Pro customers",
    company: "Home Depot",
    role: "Pro B2B transformation",
    section: "Resume through-line",
    focus: ["Product thinking", "Partnering"],
    rows: [
      { label: "Action", text: "I defined the UX strategy for moving more than two million Pro customers to a new platform, established governance across decentralized teams, and used usability studies, A/B tests, and behavioral analysis to optimize order management." },
      { label: "Result", text: "The strategy became the umbrella for acquisition migration, roles and permissions, governance, and accessibility work at enterprise scale." },
      { label: "Learned", text: "A transformation strategy needs both a shared direction and governance that lets decentralized teams execute it." },
    ],
    probe: "If asked about the hardest migration moment, use the acquisition story. If asked about consistency, use governance and the guild.",
    prompt: "How have you set strategy across multiple decentralized teams?",
  },
  {
    id: "ai-principles-dashboard",
    title: "Experience principles for AI commerce",
    company: "eBay",
    role: "AI principles + feedback-loop dashboard",
    section: "Resume through-line",
    focus: ["Product thinking"],
    rows: [
      { label: "On the resume", text: "Established future-forward experience principles for AI-assisted commerce, designed a task-management dashboard enabling personalization feedback loops, and connected fragmented initiatives into scalable systems." },
      { label: "Why it matters", text: "Principles that outlive a project are a clear director-level signal. A manager will ask what the principles were and who uses them now." },
      { label: "Prepare", text: "Name three principles out loud: clarify before acting; agent signals live inside the existing surface; every agent action has a visible undo or feedback path. Add one sentence on the loop the dashboard closed and for whom." },
    ],
    probe: "This is currently marked “untold.” Strengthen it with the team or product decisions the principles now guide.",
    prompt: "Tell me about a principle or system you created that outlived the project.",
  },
  {
    id: "home-depot-living-preread",
    title: "The living pre-read that changed the conversation",
    company: "Home Depot",
    role: "Senior UX Designer · 2018–2022",
    section: "Proactive communication",
    focus: ["Communicating", "Partnering"],
    flags: ["Cross-functional acceleration"],
    rows: [
      { label: "Situation", text: "The project was complex, moved through multiple milestones, and needed sustained buy-in from development, product managers, senior staff, and leadership. I also saw an opportunity to make the case for additional resources." },
      { label: "Action", text: "I created a concise presentation deck that summarized the work, decisions, and current design direction. I attached it to meeting invitations so partners could review it beforehand, and I kept it current as comps and design iterations changed." },
      { label: "Result", text: "Partners came into meetings with the same context, which let us spend less time recapping and more time resolving implementation decisions and real blockers. The shared artifact increased stakeholder buy-in, created leverage for resourcing and implementation, and kept milestones moving across the project. I describe this as accelerated delivery rather than assigning a number of months without a baseline and revised timeline." },
      { label: "Learned", text: "Proactive communication is not simply sending an update. It is designing the conditions for a better decision before the meeting begins." },
    ],
    say: "I treated the deck as a living pre-read, not a presentation artifact. It gave every discipline the same context before the meeting, built sustained buy-in, and turned our live time into decisions about implementation, resourcing, and the problems blocking progress.",
    avoid: "“I put together a deck.” That understates the leadership move. Emphasize how you changed the quality and purpose of the cross-functional conversation.",
    probe: "The defensible pattern is accelerated delivery through stakeholder buy-in and leverage. Add the project name and one concrete decision, resource, risk, or blocker when you remember it. Do not say ‘months faster’ without an original and revised timeline.",
    prompt: "Tell me about a time you communicated proactively to align a complex cross-functional project.",
  },
  {
    id: "ebay-search-newsletter-ai-language",
    title: "One search newsletter, one language for AI",
    company: "eBay",
    role: "Staff Product Designer · 2024–2026",
    section: "Proactive communication",
    focus: ["Communicating", "Product thinking"],
    flags: ["Add evidence"],
    rows: [
      { label: "Situation", text: "Search initiatives were moving across multiple teams, while emerging AI experiences needed a clearer and more consistent way to distinguish firm instructions from flexible guidance." },
      { label: "Action", text: "I created a newsletter that brought eBay’s search initiatives into one recurring communication. In parallel, I began formalizing directive versus permissive language for AI interactions and structured the communication architecture so guidance could be updated easily as the system evolved." },
      { label: "Why it mattered", text: "The newsletter gave teams a shared view of work that had previously been fragmented. The reusable language structure was designed to make updates easier and help the AI interpret changing guidance more consistently." },
      { label: "Learned", text: "Communication can become product infrastructure. When information is modular, explicit, and easy to maintain, it helps both people and AI systems operate with less ambiguity." },
    ],
    say: "I solved two versions of the same communication problem: helping teams see the full search portfolio and helping the AI distinguish what it must do from where it has room to adapt.",
    avoid: "Do not leave this at “I started a newsletter.” Connect the editorial system and AI language architecture to a specific coordination or product outcome.",
    probe: "Add the newsletter audience and cadence, one example of directive versus permissive language, and evidence that the approach improved adoption, update speed, AI behavior, or decision quality.",
    prompt: "Tell me about a communication system you created before the organization asked for one.",
  },
  {
    id: "adplist-designing-for-comprehension",
    title: "Designing the message for comprehension",
    company: "ADPList",
    role: "Volunteer Design Mentor · Pandemic era and 2024",
    section: "Adaptive communication",
    focus: ["Communicating", "Growing continuously"],
    flags: ["Clarify scale"],
    rows: [
      { label: "Situation", text: "I mentored designers through ADPList during two periods of major professional disruption: the pandemic and the rapid AI shift in 2024. The designers brought different needs, anxieties, and ways of processing information to each conversation." },
      { label: "Action", text: "I did not assume everyone absorbed information in the same way. I first identified how each person preferred to receive guidance, then chose the format. When one designer struggled to understand text and chat-based instructions, I translated the same direction into an infographic." },
      { label: "Result", text: "The change in format helped the designer grasp the guidance more clearly. I also helped the mentees refine their portfolios and gave specific recommendations for strengthening how they presented their work. They applied that feedback and ultimately secured jobs." },
      { label: "Learned", text: "The goal of communication is not simply to send a clear message. It is to create comprehension, and that sometimes requires changing the medium rather than the message." },
    ],
    say: "I start by learning how someone prefers to receive information, because clarity from the sender does not guarantee comprehension for the receiver.",
    avoid: "Do not describe someone as permanently being a “visual learner.” Focus on observing what was not working, adapting the format, and checking that the new approach created understanding.",
    probe: "Clarify whether the four months covered one mentoring period or both, how many designers you supported, and what kinds of roles they secured. If possible, connect the infographic directly to the portfolio improvement it unlocked.",
    prompt: "Tell me about a time you adapted your communication style to help someone succeed.",
  },
  {
    id: "career-scope-and-restraint",
    title: "From one workflow to a global marketplace",
    company: "Home Depot · Walmart · eBay",
    role: "Résumé fluency through expanding scope and judgment",
    section: "Résumé fluency",
    focus: ["Growing continuously", "Product thinking"],
    flags: ["Career arc", "Clarify timeline"],
    rows: [
      { label: "Growth pattern", text: "As I became more versed in retail and ecommerce, I deliberately took on harder problems with more participants, markets, tools, and category-specific constraints. The progression was not complexity for its own sake; it required me to improve how I frame systems, choose the right level of intervention, and protect experience quality as the number of variables grows." },
      { label: "Home Depot", text: "My scope centered on Home Depot Pro customers in one US market and one internal tool. That environment taught me the foundations of B2B retail workflows, professional-customer needs, and how internal operations shape the customer experience." },
      { label: "Home Depot → Walmart", text: "I left Home Depot voluntarily because my role and learning had plateaued. I wanted broader marketplace and platform experience, and Walmart offered the opportunity to expand from one customer group, tool, and market to merchants and suppliers across a much larger product ecosystem. I transitioned after delivering my core work and leaving the team with a usable foundation." },
      { label: "Walmart", text: "My scope expanded to both merchants and suppliers, more than 100 fragmented tools, and marketplaces across the United States, Canada, and Mexico. I had to understand both sides of the operating relationship and turn a large application ecosystem into a more coherent platform strategy." },
      { label: "Walmart → eBay", text: "Walmart later terminated my employment. Earlier in my tenure, I had completed an extended performance process, but trust with my manager did not fully recover. The experience taught me to establish objective success criteria, communication cadence, ownership, decision rights, and escalation paths much earlier. It also taught me that identifying the right strategic dependency does not by itself authorize me to decide how the organization resolves it. I had invested independently in management training and chose eBay because its global, multi-sided marketplace made systems-level product thinking an explicit part of the work." },
      { label: "eBay", text: "The system expanded again to buyers, sellers, and third parties; multiple product surfaces; global marketplaces; and categories with very different levels of consideration, trust, condition, regulation, and fulfillment complexity. A pattern that works for a low-risk commodity may fail for a collectible, vehicle, luxury item, or cross-border purchase." },
      { label: "eBay → next opportunity", text: "My role at eBay was eliminated in a reorganization. I was disappointed because I loved the work, had strong relationships with my partners, and had built the business knowledge needed to scale my contribution. Since the layoff, I have continued independently exploring agentic search, local discovery, and category-specific commerce—not as work for eBay, but because I believe these are important product problems. I am looking for an environment where I can apply that foundation to a high-impact AI product and translate future-state thinking into a staged, executable strategy." },
      { label: "What actually grew", text: "The visible growth was larger scope, but the more important growth was judgment. I learned to distinguish essential complexity from organizational noise, identify the few variables that should shape the experience, and resist exposing the entire system to the customer." },
      { label: "Restraint and taste", text: "In highly complex environments, quality often comes from editing. I use progressive disclosure, clear principles, evidence gates, and a coherent experience hierarchy to decide what not to add. Restraint is how I preserve usability and taste without oversimplifying the marketplace behind the interface." },
    ],
    say: "My transitions were not all voluntary. I chose to leave Home Depot to expand my marketplace scope; Walmart ended in termination and taught me to pair strategic foresight with explicit alignment on authority, expectations, and trust; and eBay ended in a reorganization while I was preparing to scale the foundation I had built. Across each experience, I delivered reusable work, expanded the complexity I could handle, and developed more restraint in what I brought forward to the customer.",
    avoid: "Do not claim that every move happened because a better opportunity appeared. Do not say Walmart fired you for performing at Principal level or because your system made you unnecessary. Do not speculate about sexual favoritism, ego, a fake severance process, or being a sacrificial lamb. Describe the Walmart termination and eBay reorganization directly, separate verified facts from interpretation, and never describe your independent post-layoff exploration as continuing to work for eBay.",
    probe: "Confirm Walmart's documented termination reason, the exact duration of the formal performance process, and how much time passed between completing it and termination. Confirm eBay's official reorganization language. Add one delivered outcome and one concrete handoff from each company.",
    prompt: "How have your scope and product judgment grown across your career?",
  },
  {
    id: "nyc-tech-week-design-representative",
    title: "Showing up where design wasn’t in the room",
    company: "NYC Tech Week",
    role: "Design representative · Cross-disciplinary learning",
    section: "Growth opportunity",
    focus: ["Growing continuously", "Partnering", "Product thinking", "Driving results"],
    flags: ["Add evidence"],
    rows: [
      { label: "Opportunity", text: "At NYC Tech Week, I participated in demo sessions featuring new AI plugins, models, and product launches. There were not many designers in the room, which made the opportunity more valuable rather than less relevant to design." },
      { label: "Action", text: "I deliberately joined conversations outside the traditional design track so I could learn how emerging technology was being framed by product leaders and developers. I treated myself as the design representative—looking for opportunities to partner, contribute, and lead across disciplines and organizational levels." },
      { label: "Translation", text: "As I evaluated each idea, I anticipated how a product person might assess its value and tradeoffs versus how a developer might assess feasibility, architecture, or risk. I used those different lenses to shape how I asked questions and communicated the design perspective." },
      { label: "Amplification", text: "I do not keep the learning to myself. I share demos, workflow unlocks, and more efficient ways of working through LinkedIn posts and blog articles, explaining emerging tools through a systems-design lens so the broader design community can apply them." },
      { label: "Application", text: "I use that same systems lens to break problems down to first principles: what are we actually solving, why does it matter, how do the parts interact, and where can a new workflow create leverage? That helps me move beyond adopting tools toward using them intentionally to drive better results." },
      { label: "Learned", text: "Design leadership creates more value when it participates before decisions become a design brief, translates across disciplines, and turns individual learning into reusable leverage for others." },
    ],
    say: "I intentionally go where design is underrepresented, translate what I learn across product and engineering lenses, and then turn that learning into practical guidance other designers can use.",
    avoid: "Do not frame being early to a tool or attending an event as the achievement. The leadership signal is how you evaluate the technology, share the learning, and convert it into better systems or results.",
    probe: "Name one article or workflow unlock, the audience it reached, and a concrete result: time saved, a workflow adopted, a design approach changed, or a product decision influenced.",
    prompt: "Tell me about a growth opportunity you pursued outside your immediate discipline.",
  },
  {
    id: "tasb-insiderm-two-sided-product",
    title: "InsideRM: one product for readers and publishers",
    company: "TASB",
    role: "Lead UX Designer · 2017–2018",
    section: "Portfolio archive",
    focus: ["Driving results", "Product thinking", "Partnering"],
    flags: ["Public metrics", "Reusable platform"],
    rows: [
      { label: "Situation", text: "TASB’s Risk Management Fund had published a useful quarterly newsletter since 2008, but the material was buried in an unsearchable archive and audience engagement had declined. The product had two distinct user groups: school-district professionals trying to find guidance and internal editors trying to publish and organize it." },
      { label: "Action", text: "I combined stakeholder interviews, analytics, customer surveys, a content audit, and CMS research to turn the archive into the InsideRM blog. I used future-proof categories and subcategories as the information architecture, designed three responsive templates, simplified the publishing workflow, and added analytics infrastructure for post-launch optimization." },
      { label: "Publisher outcome", text: "The CMS structure let editors create and organize stories through categories instead of manually maintaining an archive. The design was reused as the template for additional TASB blogs, extending the work beyond the original Risk Management Fund experience." },
      { label: "Reader outcomes", text: "The public case study reports a final bounce rate of 25%—a 53% reduction—average session duration of 3 minutes 26 seconds, a 111% increase in engagement, and a 40% increase in homepage visits." },
      { label: "Recognition", text: "The work earned an NSPRA Publications and Digital Media Award of Excellence." },
      { label: "Learned", text: "A content product succeeds only when discovery works for readers and the operating model works for publishers. Designing both sides created the scale." },
    ],
    source: { label: "View the InsideRM portfolio case study", url: "https://liadivalentin.com/tasb-rmf-blog-redesign" },
    say: "I designed InsideRM as a two-sided product: a findable, measurable resource for readers and a sustainable publishing system for editors. That combination increased engagement 111% and made the design reusable across other TASB blogs.",
    avoid: "Do not say bounce rate improved by 25%. The final bounce rate was 25%, representing a reported 53% reduction.",
    probe: "Confirm the analytics measurement window and whether the 111% engagement metric represented events, engaged sessions, or another definition before using that detail under heavy questioning.",
    prompt: "Tell me about a product where you improved both the customer experience and the internal operating model.",
  },
  {
    id: "army-10k-content-system",
    title: "Army.mil: turning 10,000 pages into a navigable system",
    company: "SAIC / U.S. Army",
    role: "UX Designer · 2014–2016",
    section: "Portfolio archive",
    focus: ["Product thinking", "Partnering", "Driving results"],
    flags: ["Scale story", "Legacy constraints"],
    rows: [
      { label: "Situation", text: "Army.mil had more than 10,000 indexed pages and assets, inconsistent navigation and branding, abandoned content, duplicate information, and more than 1,000 broken links and 404 pages. The site was also an underused support channel even though it served as the Army’s public digital front door." },
      { label: "Constraints", text: "The redesign had to work with the Army’s homegrown legacy CMS, remain compatible with Internet Explorer 9, meet Section 508 accessibility requirements, and navigate a decentralized Department of Defense governance structure." },
      { label: "Action", text: "I mapped the technical ecosystem, facilitated an opportunity workshop, audited the content and analytics, ran online card-sorting studies, and worked with stakeholders to consolidate the information architecture. I also partnered with developers to define reusable templates and a component pattern library that the existing CMS could support." },
      { label: "Result", text: "The work produced a cleaner site map, evidence-based navigation language, more visible high-demand links, and a modular foundation for the redesigned Army.mil experience. The broader Army.mil work received a Department of Defense Thomas Jefferson Award for Outstanding Flagship Website." },
      { label: "Learned", text: "At large-system scale, visual redesign is downstream of content governance, technical reality, and organizational alignment. The design work begins by making the system legible." },
    ],
    source: { label: "View the Army.mil redesign case study", url: "https://liadivalentin.com/armyhomepageredesign" },
    say: "Before designing a page, I made a 10,000-page ecosystem legible—content, governance, analytics, and technical constraints—then used that evidence to create the navigation and modular system.",
    avoid: "Do not collapse this into a visual redesign story. The differentiator is the scale of the audit, the facilitation, and the legacy-system judgment.",
    probe: "Recover a post-launch navigation, support-contact, broken-link, or task-completion result if one exists. Keep the 10,000 pages and 1,000 broken links tied to the pre-redesign audit.",
    prompt: "Tell me about a complex legacy product where you had to make the system understandable before you could redesign it.",
  },
  {
    id: "army-app-learnability-walkthrough",
    title: "Army app: when hesitation changed first-run education",
    company: "SAIC / U.S. Army",
    role: "UX Designer · 2014–2016",
    section: "Portfolio archive",
    focus: ["Growing continuously", "Product thinking", "Communicating"],
    flags: ["Research insight", "Add outcome"],
    rows: [
      { label: "Situation", text: "The existing Army News and Information app had broken galleries, duplicate content, readability complaints, and disorienting navigation that caused users to abandon tasks." },
      { label: "Research", text: "I reviewed user-feedback surveys, compared four related news and military-service apps, developed two personas from interviews, aligned success criteria with stakeholders, and tested the emerging interaction model." },
      { label: "Insight", text: "Users over age 45 showed a noticeable three-to-five-second hesitation when encountering unfamiliar interaction cues. They often discovered the behavior and formed a lasting association, which showed that the pattern was learnable but not immediately discoverable." },
      { label: "Action", text: "Instead of discarding the interaction, I added a concise first-launch walkthrough that introduced the unfamiliar patterns and explained the most important functionality before users entered the experience." },
      { label: "Result to recover", text: "The portfolio documents the behavioral finding and the resulting design revision, but it does not include a post-change completion, hesitation, adoption, or satisfaction metric. Preserve the story and add that outcome if it can be recovered." },
      { label: "Learned", text: "Learnability and discoverability are different. A pattern can become understandable after exploration and still need carefully scoped education at the first moment of use." },
    ],
    source: { label: "View the Army News app case study", url: "https://liadivalentin.com/app" },
    say: "Testing showed me that the interaction was learnable but not immediately discoverable, so I added targeted first-run education instead of abandoning an otherwise effective pattern.",
    avoid: "Do not present the three-to-five-second hesitation as a post-launch improvement. It was the research observation that triggered the design change.",
    probe: "Add the number of participants, the tested task, and any before-and-after completion or hesitation observation you remember.",
    prompt: "Tell me about a research insight that caused you to revise a product without throwing away the underlying interaction.",
  },
  {
    id: "women-army-stakeholder-compromise",
    title: "Women in the Army: preserving structure through compromise",
    company: "SAIC / U.S. Army",
    role: "UX Designer · 2014–2016",
    section: "Portfolio archive",
    focus: ["Partnering", "Communicating", "Product thinking"],
    flags: ["Disagreement story", "Add adoption evidence"],
    rows: [
      { label: "Situation", text: "The Army produced monthly campaign microsites from four nonresponsive templates. For Women’s History Month, I was asked to redesign the heritage experience in a way that could support many future campaigns and very different kinds of content." },
      { label: "Disagreement", text: "I recommended placing news, videos, and related links on a dedicated resources page. The client strongly preferred putting all Army.mil content on the introductory landing page." },
      { label: "Action", text: "I accepted the client’s communication priority without giving up the usability goal. I reorganized the landing page into distinct content sections, added a responsive Army video playlist, and used modular profile cards with progressive disclosure so the denser page still had hierarchy." },
      { label: "System intent", text: "The components were deliberately flexible because the design was intended to become the new heritage-microsite template, supporting different campaigns, profiles, media, histories, and resource needs." },
      { label: "Result to recover", text: "The portfolio establishes the compromise and reusable-template requirement, but it does not document how many later heritage sites adopted the pattern or what the client and users reported after launch." },
      { label: "Learned", text: "Productive disagreement is not winning the original layout. It is identifying the stakeholder’s nonnegotiable goal and finding another structure that protects comprehension and reuse." },
    ],
    source: { label: "View the Women in the Army case study", url: "https://liadivalentin.com/womeninthearmy" },
    say: "I did not get the content split I recommended, so I protected the underlying goals—hierarchy, responsiveness, and reuse—inside the client’s preferred landing-page model.",
    avoid: "Do not frame the client as wrong or the compromise as reluctant compliance. Explain the competing goals and the structure you created to satisfy both.",
    probe: "Recover one stakeholder reaction and the number or names of later heritage microsites that reused the template. That evidence determines whether this becomes an anchor or remains a backup.",
    prompt: "Tell me about a time you disagreed with a stakeholder and found a solution that preserved both business intent and usability.",
  },
];

const framingRules = [
  ["Decision first, design second.", "Open with the call you made and why, then what you designed. Seniors describe work; principals describe judgment."],
  ["“I” for decisions, “we” for execution.", "Name your ownership clearly, then give the team credit for how the work came to life."],
  ["Scope up one level in the sentence.", "Not “I built a subsystem,” but “I removed the organization’s velocity bottleneck.”"],
  ["End with what outlived you.", "A principle, SOP, system, trained team, or operating model is the director signal."],
  ["Use the business’s language.", "Weeks saved, dollars, ROI, conversion, and risk belong beside the user case."],
  ["Let ambition land as service.", "Show what you built for others. Let the interviewer conclude that you were ahead of the curve."],
  ["Keep growth stories human.", "Own the miss, sharpen the lesson, and prove you applied it later."],
  ["Separate evidence from precision.", "A named adopter and a visible analytics trend are credible evidence even when the exact count is unknown. Never turn an observed spike into an invented adoption total or an unmeasured speed multiplier."],
];

const practicePrompts = [
  { focus: "Partnering", prompt: "Tell me about a partnership that changed the outcome of a project.", storyId: "acquisition-onboarding" },
  { focus: "Partnering", prompt: "Tell me about a time you disagreed with a team and still helped them succeed.", storyId: "storybook-bet" },
  { focus: "Communicating", prompt: "Tell me about a time you communicated proactively to align a complex cross-functional project.", storyId: "home-depot-living-preread" },
  { focus: "Communicating", prompt: "Tell me about a communication system you created before the organization asked for one.", storyId: "ebay-search-newsletter-ai-language" },
  { focus: "Communicating", prompt: "Tell me about a time you adapted your communication style to help someone succeed.", storyId: "adplist-designing-for-comprehension" },
  { focus: "Communicating", prompt: "How do you communicate complex systems to very different stakeholders?", storyId: "roles-permissions" },
  { focus: "Communicating", prompt: "Tell me about a time you changed how a team worked.", storyId: "ai-workflow-sprints" },
  { focus: "Driving results", prompt: "Tell me about a 0→1 initiative you drove from ambiguity to launch.", storyId: "supplier-one" },
  { focus: "Driving results", prompt: "How have you delivered impact without formal authority?", storyId: "figma-subsystem" },
  { focus: "Partnering", prompt: "Tell me about a capability your team built that another team chose to adopt.", storyId: "figma-subsystem" },
  { focus: "Growing continuously", prompt: "Tell me about something you got wrong and what changed afterward.", storyId: "size-overbuild" },
  { focus: "Growing continuously", prompt: "Tell me about a hypothesis you challenged and converted into a stronger product strategy.", storyId: "local-pickup" },
  { focus: "Growing continuously", prompt: "How have your scope and product judgment grown across your career?", storyId: "career-scope-and-restraint" },
  { focus: "Growing continuously", prompt: "Walk me through your career and why you made each major transition.", storyId: "career-scope-and-restraint" },
  { focus: "Growing continuously", prompt: "Tell me about a growth opportunity you pursued outside your immediate discipline.", storyId: "nyc-tech-week-design-representative" },
  { focus: "Product thinking", prompt: "Tell me about a time you reframed the problem and changed the strategy.", storyId: "size-journey" },
  { focus: "Product thinking", prompt: "Tell me about a system that moved designers from production work to higher-order product thinking.", storyId: "figma-subsystem" },
  { focus: "Product thinking", prompt: "Tell me about a product risk nobody else owned.", storyId: "video-infrastructure" },
  { focus: "Product thinking", prompt: "How do you design trust when an AI system can be wrong?", storyId: "ai-shopping-agent" },
  { focus: "Growing continuously", prompt: "Tell me about a direction that went against your personal design vision.", storyId: "storybook-bet" },
];

const interviewQuestions = [
  "How do design decisions on AI products get made here—who owns the moments when the agent is wrong?",
  "Where does design have the most influence on strategy on this team, and where would you like it to have more?",
  "What does a strong first six months look like for this role?",
];


const resumeProfile = {
  name: "Lia DiValentin",
  headline: "Product Design Leader · AI Commerce, Search & Discovery",
  location: "New York, NY",
  email: "ladivalent@gmail.com",
  phone: "703-625-0862",
  portfolio: "https://liadivalentin.com",
  linkedin: "https://www.linkedin.com/in/liadivalentin",
  summary:
    "Product design leader with 10+ years shaping commerce, marketplace, and enterprise experiences at global scale. I turn ambiguous opportunities into clear product direction, connect strategy to crafted end-to-end interaction, and build reusable systems that help teams move faster. My recent work spans agentic shopping, AI-assisted search, personalization, marketplace infrastructure, and complex B2B workflows.",
};

const resumeHighlights = [
  {
    value: "Patent inventor",
    label: "eBay flip item card · U.S. application 19/002,651",
  },
  {
    value: "48 → 5 days",
    label: "Supplier onboarding cycle reduced at Walmart",
  },
  {
    value: "1M+ customers",
    label: "Migration supported through Home Depot onboarding",
  },
  {
    value: "100+ tools",
    label: "Supplier landscape consolidated through Supplier One",
  },
];

const resumeRoles = [
  {
    company: "eBay",
    title: "Staff Product Designer",
    dates: "June 2024 – March 2026",
    scope: "AI-powered shopping and discovery · Global marketplace · Consumer web and mobile",
    summary:
      "Led product direction and interaction design across AI shopping, search, discovery, personalization, and the systems connecting those experiences.",
    bullets: [
      "Led end-to-end UX for eBay’s AI Shopping Agent, a conversational experience that turns broad intent into guided product discovery and shipped as a controlled U.S. production pilot.",
      "Redesigned the Search Results Page ecosystem—including zero state, autocomplete, filters, item cards, ads, and top-of-funnel discovery—to support AI-first browsing while preserving familiar marketplace behavior.",
      "Named inventor on Immersive Item Cards, a flip-card interaction that reveals AI-curated signals inside high-density product grids without permanently increasing interface density (U.S. application 19/002,651; publication US 2026/0187710 A1).",
      "Established experience principles for AI-assisted commerce, including how the product communicates uncertainty, handles failure, uses progressive disclosure, and returns control when a recommendation misses.",
      "Created an end-to-end conceptual framework connecting buyer and seller journeys, with a personalization task dashboard that turns behavior and feedback into more useful recommendations.",
      "Built a 200+ variant component-logic matrix and introduced AI-assisted research and prototyping workflows that improved consistency between design intent and implementation.",
      "Mentored designers and aligned Product, Engineering, Data Science, and Research leaders around roadmaps, tradeoffs, and reusable interaction patterns.",
    ],
    projectLinks: [
      { label: "Fashion Magical Search", href: "https://liadivalentin.com/ebay-fashion-magical-search" },
      { label: "Hybrid User Experience", href: "https://liadivalentin.com/ebay-hybrid-user-experience" },
    ],
  },
  {
    company: "Walmart",
    title: "Senior Product Designer",
    dates: "June 2022 – April 2024",
    scope: "B2B ecommerce · Supplier platform · Inventory and order management · Design systems",
    summary:
      "Led 0-to-1 design for Supplier One, a unified platform for suppliers to onboard, set up items, manage inventory, and process orders.",
    bullets: [
      "Consolidated a landscape of more than 100 supplier-facing tools into a unified experience and helped take Supplier One from concept through its February 2024 U.S. launch.",
      "Reduced average supplier onboarding from 48 days to 5 days, measured from application start through approval; the first launch successfully onboarded 500+ high-revenue suppliers and achieved the 30% invited-supplier conversion goal.",
      "Reduced the combined measure of support tickets and call-center contacts by 20% after launch.",
      "The unified platform contributed to an approximately 30% reduction in logistics costs and approximately 4× ROI during the first six months after launch.",
      "Built an internal design subsystem and reusable component library, then taught the team to use Figma adoption data to demonstrate value and identify opportunities for cross-team collaboration.",
      "Applied mixed-methods research, usability testing, and A/B experimentation to simplify high-volume supplier workflows; mentored designers and led cross-functional design-thinking workshops.",
    ],
    projectLinks: [
      { label: "Walmart Supplier One", href: "https://liadivalentin.com/walmart-supplier-one" },
    ],
  },
  {
    company: "The Home Depot",
    title: "Senior User Experience Designer",
    dates: "October 2018 – June 2022",
    scope: "Omnichannel retail · B2B Pro platform · Account and order management",
    summary:
      "Owned complex Pro account-management and onboarding experiences spanning roles, permissions, groups, migration, and enterprise workflows.",
    bullets: [
      "Owned end-to-end UX for Home Depot Pro’s account ecosystem, including roles, permissions, groups, and enterprise workflows on a platform serving more than 2 million professional customers.",
      "Defined UX strategy and onboarding flows that supported the migration of more than 1 million acquired customers—including large contractors, small contractors, and individual businesses—into the new login and account platform.",
      "Identified a schema and address-model risk early enough to avoid approximately six weeks of engineering rearchitecture; the roughly $1 million impact is an internal estimate based on the avoided effort.",
      "Created living pre-read decks that helped Product, Engineering, and leadership understand design changes before meetings, increasing the time available for decisions and implementation planning.",
      "Ran usability studies, A/B tests, surveys, and behavioral analysis across account and order-management flows.",
      "Led the internal accessibility guild, producing standards and operating guidance that embedded WCAG 2.1 AA practices into decentralized agile teams.",
    ],
    projectLinks: [
      { label: "B2B Pro Experience", href: "https://liadivalentin.com/thehomedepotb2bexperience" },
      { label: "B2B User Management", href: "https://liadivalentin.com/home-depot-b2b-user-management" },
    ],
  },
];

const earlierRoles = [
  {
    company: "Texas Association of School Boards",
    title: "Lead UX Designer",
    dates: "2017 – 2018",
    scope: "Education · Digital publishing · Accessibility",
    summary:
      "Directed the research and information-architecture strategy for TASB.org, created an organization-wide design system, and integrated third-party service experiences.",
    bullets: [
      "Established WCAG 2.1 AA standards for new digital work and earned an NSPRA Publications and Digital Media Award of Excellence.",
    ],
  },
  {
    company: "Bulldog Solutions",
    title: "UX Designer",
    dates: "2016 – 2017",
    scope: "B2B marketing · Responsive web · Campaign experiences",
    summary:
      "Designed responsive websites, landing pages, newsletters, and campaign experiences for clients including Box, Oracle, TD Ameritrade, Silicon Labs, and Frontier Communications.",
    bullets: [],
  },
  {
    company: "SAIC · U.S. Army Public Affairs, Pentagon",
    title: "UX Designer",
    dates: "2014 – 2016",
    scope: "Government and defense · Digital publishing · Native mobile",
    summary:
      "Led UX for the Army.mil redesign and U.S. Army News iOS app, introduced research and design-thinking practices, and established the first open-source component library for Army digital properties.",
    bullets: [
      "Awarded the Department of Defense Thomas Jefferson Award for the Army’s flagship website; held a Secret security clearance in 2014.",
    ],
  },
];

const resumeCapabilities = [
  {
    label: "Product and interaction",
    items: ["0-to-1 product definition", "End-to-end flow design", "Interaction pattern invention", "Coded and high-fidelity prototyping", "Design systems"],
  },
  {
    label: "AI, search and commerce",
    items: ["Agentic and conversational commerce", "AI-assisted search and discovery", "Personalization", "Marketplace systems", "Trust, uncertainty and failure states"],
  },
  {
    label: "Research and strategy",
    items: ["Mixed-methods research", "A/B testing", "Usability testing", "Behavioral analysis", "Evidence-led product strategy", "Progressive disclosure"],
  },
  {
    label: "Leadership",
    items: ["Executive storytelling", "Cross-functional alignment", "Mentorship and coaching", "Roadmap influence", "Accessibility governance", "Systems thinking"],
  },
  {
    label: "Tools",
    items: ["Figma", "Figma Make", "Claude", "ChatGPT", "Google NotebookLM", "VS Code", "HTML/CSS/JavaScript", "Adobe Creative Cloud", "Miro", "UserTesting.com"],
  },
];

const resumeEducation = [
  {
    credential: "BFA, Graphic Design",
    institution: "George Mason University",
    detail: "GPA 3.8 · Dean’s List",
  },
  {
    credential: "Master’s Certificate in UX Management",
    institution: "Nielsen Norman Group",
    detail: "100+ hours of training · 15 exams",
  },
  {
    credential: "IDEO U continuing education",
    institution: "IDEO U",
    detail: "AI x Design Thinking · Human-Centered Systems Thinking · Leading Complex Projects · Innovating with Data · Designing for Change · Insights for Innovation",
  },
];

const resumeRecognition = [
  "Named inventor — Immersive Item Cards, U.S. application 19/002,651; publication US 2026/0187710 A1",
  "Department of Defense Thomas Jefferson Award — Army.mil",
  "NSPRA Publications and Digital Media Award of Excellence",
  "GMU School of Art Writing Across the Curriculum honorable mentions",
];

const resumeEvidenceNotes = [
  "The AI Shopping Agent reached a controlled U.S. production pilot. Public eBay materials describe the audience as a small subset; the approximately 1% cohort is internal rollout knowledge.",
  "Supplier One’s 80/100 ASUS customer-satisfaction figure was the target, not the recovered post-launch score, so it is intentionally omitted from the résumé.",
  "The Home Depot $1 million impact is an internal estimate derived from roughly six weeks of avoided engineering and rearchitecture effort.",
  "The patent record is presented by its application and publication identifiers. Replace this wording with a grant number only after the grant record is recovered.",
];


window.GUIDE_DATA = { focusAreas, anchorStoryMap, evidenceClassifications, stories, framingRules, practicePrompts, interviewQuestions, resumeProfile, resumeHighlights, resumeRoles, earlierRoles, resumeCapabilities, resumeEducation, resumeRecognition, resumeEvidenceNotes };
})();
